name: CI/CD on Pull Request

on:
  push:
    branches:
      - main

jobs:
  pull_request:
    uses: jiw-kittipong/github-action-workflows/.github/workflows/dotnet-ci-cd.yml@main
    with: 
      application_name: "my-app"
      code_language: "dotnet"

#      dotnet_version: "6.0.0"
#      dotnet_project_path: "src/dotnet-example.API"
#      dotnet_test_enabled: "true"

