name: CI/CD on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  pull_request:
    uses: jiw-kittipong/github-action-workflows/.github/workflows/dotnet_pipeline.yml@main
    with: 
      application_name: "dotnet-example-api"
      code_language: "dotnet"
      
      dotnet_version: "6.0"
      dotnet_project_path: "src/dotnet-example.API"
      dotnet_test_enabled: true

    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
# 1 2 3
